spring:
  cloud:
    # Sentinel 配置项，对应 SentinelProperties 配置属性类
    sentinel:
      enabled: true                   # 是否开启。默认为 true 开启
      eager: true                     # 是否饥饿加载。默认为 false 关闭
      transport:
        dashboard: 127.0.0.1:28858    # Sentinel 控制台地址，控制台连接业务服务
      filter:
        url-patterns: /**             # 拦截请求的地址。默认为 /*
#      log:
#        dir:
  # Sentinel 规则的数据源，是一个 Map 类型。key 为数据源名，可自定义；value 为数据源的具体配置
#      datasource:
#        ds1:
#          # 对应 DataSourcePropertiesConfiguration 类
#          nacos:
#            server-addr: 127.0.0.1:28848  # Nacos 服务器地址
#            namespace:                    # Nacos 命名空间
#            group-id: DEFAULT_GROUP
#            data-id: ${spring.application.name}-flow-rule # Nacos 配置集编号
#            data-type: json               # 数据格式
#            rule-type: FLOW               # 规则类型

#    nacos:
#      config:
#        server-addr: 127.0.0.1:28848
#        namespace:              # 使用的 Nacos 的命名空间，默认为 null
#        group: DEFAULT_GROUP    # 使用的 Nacos 配置分组，默认为 DEFAULT_GROUP
#        name:                   # 使用的 Nacos 配置集的 dataId，默认为 spring.application.name
#        file-extension: yaml    # 使用的 Nacos 配置集的 dataId 的文件拓展名，同时也是 Nacos 配置集的配置格式，默认为 properties
