version: '3.9'
services:
  # https://hub.docker.com/_/mysql
  msa-mysql:
    container_name: msa-mysql
    hostname: msa-mysql
    image: mysql:8.0.32
    #command: "--default-authentication-plugin=mysql_native_password" # 可以放配置文件中
    #restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "23306:3306"
    volumes:
      - ./mysql/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./mysql/data:/var/lib/mysql
      - ./mysql/sql:/docker-entrypoint-initdb.d   # 容器首次初始化阶段会执行内部的  .sh .sql .sql.gz
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 15s
    networks:
      - msa-action-network

  # https://hub.docker.com/_/phpmyadmin
  msa-phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: msa-phpmyadmin
    hostname: msa-phpmyadmin
    ports:
      - "20080:80"
    environment:
      - PMA_HOST=msa-mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - msa-action-network
    depends_on:
      msa-mysql:
        condition: service_healthy

  # https://hub.docker.com/_/redis
  msa-redis:
    container_name: msa-redis
    image: redis:6.2.13
    hostname: redis
    privileged: true
    ports:
      - "26379:6379"
    volumes:
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      #- ./redis/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - msa-action-network

  # Redis 控制台 https://github.com/joeferner/redis-commander
  # 账密 admin/admin
  msa-redis-admin:
    container_name: msa-redis-admin
    image: spryker/redis-commander:0.8.0
    hostname: redis-commander
    #restart: always
    ports:
      - "26391:8081"
    environment:
      # https://github.com/joeferner/redis-commander?tab=readme-ov-file#valid-host-strings-used-for-redis_hosts
      - REDIS_HOST=msa-redis
      - REDIS_PASSWORD=123456
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
      - LANG=C.UTF-8
      - LANGUAGE=C.UTF-8
      - LC_ALL=C.UTF-8
    networks:
      - msa-action-network
    depends_on:
      msa-redis:
        condition: service_healthy

  # https://hub.docker.com/r/nacos/nacos-server
  # uri: http://localhost:28848/nacos/
  msa-nacos:
    container_name: msa-nacos
    image: nacos/nacos-server:v2.2.3-slim
    ports:
      - "28848:8848"
      - "29848:9848"
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=msa-mysql
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      - NACOS_AUTH_IDENTITY_KEY=2222
      - NACOS_AUTH_IDENTITY_VALUE=2xxx
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
    #volumes:
    #  - ./nacos/conf/application.properties:/home/nacos/conf/application.properties
    networks:
      - msa-action-network
    depends_on:
      msa-mysql:
        condition: service_healthy

  msa-zookeeper:
    image: zookeeper:3.9.0
    container_name: msa-zookeeper
    #restart: always
    ports:
      - "22181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=msa-zookeeper:2888:3888;2181
      ZOOKEEPER_CLIENT_PORT: 2181
      ALLOW_ANONYMOUS_LOGIN: yes
      TZ: Asia/Shanghai
    networks:
      - msa-action-network

  msa-kafka:
    image: bitnami/kafka:3.7.0
    container_name: msa-kafka
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - "29092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      #服务本地启动（如在IDEA中启动）连接Docker内部的kafka, 会发现监听器无法连接到kafka,
      #调试发现监听器连接kafka时连接的是msa-kafka:9092, 需要将host（msa-kafka）转成IP地址，但是本地无法使用docker的域名解析，本地应用打包成镜像后则可以，
      #需要手动配置kafka的域名映射，比如 172.18.0.6 msa-kafka， 可以通过 SwitchHosts 工具维护
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://msa-kafka:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: msa-zookeeper:2181
      #如果只启动一个Kafka节点，这里副本数应该设置为1,否则启动会报错
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_MESSAGE_MAX_BYTES: "2000000"
      KAFKA_ENABLE_KRAFT: no
      JMX_PORT: 9999
      TZ: Asia/Shanghai
    networks:
      - msa-action-network
    depends_on:
      - msa-zookeeper

  msa-kafka-eagle:
    image: echo21bash/kafka-eagle:3.0.2
    container_name: msa-kafka-eagle
    environment:
      KAFKA_EAGLE_ZK_LIST: msa-zookeeper:2181
    volumes:
      - ./kafka-eagle/system-config.properties:/opt/kafka-eagle/conf/system-config.properties
    ports:
      - "28048:8048"
    networks:
      - msa-action-network
    depends_on:
      - msa-kafka

  # 监控系统-数据采集
  msa-prometheus:
    image: bitnami/prometheus:2.47.2
    container_name: msa-prometheus
    #restart: always
    ports:
      - "29090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - msa-action-network

  # 监控系统-数据展示
  # 用户名密码：admin/admin
  msa-grafana:
    image: grafana/grafana:10.2.0
    container_name: msa-grafana
    #restart: always
    ports:
      - "24000:4000"
    volumes:
      - ./grafana:/etc/grafana
    networks:
      - msa-action-network
    depends_on:
      - msa-mysql
      - msa-prometheus

  msa-elasticsearch:
    image: elasticsearch:8.1.0
    container_name: msa-elasticsearch
    ports:
      - "29200:9200"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
    environment:
      ES_JAVA_OPTS: -Xms256m -Xmx1024m
      discovery.type: single-node
      cluster.routing.allocation.disk.watermark.low: 90%
      cluster.routing.allocation.disk.watermark.high: 95%
      cluster.routing.allocation.disk.watermark.flood_stage: 98%
      xpack.security.enabled: false
      xpack.security.http.ssl.enabled: false
    # 配置健康检查，防止依赖 ES 的容器还未等待 ES 完全启动就启动
    # https://docs.docker.com/reference/compose-file/services/#healthcheck
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail http://localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - msa-action-network

  # 各个服务 JavaAgent 配置：
  # skywalking-agent 下载解压后整个文件夹都需要复制到项目目录下
  # VM 选项：-javaagent:/home/arvin/mywork/java/micro_service/msa-action/deploy/docker-compose/skywalking/skywalking-agent.jar
  # 环境变量：SW_AGENT_NAME=msa-service-xxx;SW_AGENT_COLLECTOR_BACKEND_SERVICES=msa-skywalking-oap:11800
  # 注意开发时，服务是本地启动的，skywalking-oap是Docker容器启动的，服务是无法通过容器名解析IP地址的，后面的环境变量需要修改 SW_AGENT_COLLECTOR_BACKEND_SERVICES=localhost:21800
  msa-skywalking-oap:
    image: apache/skywalking-oap-server:9.0.0
    container_name: msa-skywalking-oap
    ports:
      - "22800:12800"
      - "21800:11800"
    environment:
      TZ: Asia/Shanghai
      SW_STORAGE: elasticsearch
      SW_CORE_REST_PORT: 12800
      SW_CORE_GRPC_PORT: 11800
      SW_STORAGE_ES_CLUSTER_NODES: msa-elasticsearch:9200
      JAVA_OPTS: -Xms256m -Xmx1G
    networks:
      - msa-action-network
    depends_on:
      # OAP总是启动异常，怀疑是ES还没完全启动OAP就启动了导致的异常，修改等待条件从默认的 service_started 改为 service_healthy
      msa-elasticsearch:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1G

  msa-skywalking-ui:
    image: apache/skywalking-ui:9.0.0
    container_name: msa-skywalking-ui
    ports:
      - "28080:8080"
    environment:
      TZ: Asia/Shanghai
      SW_OAP_ADDRESS: http://msa-skywalking-oap:12800
    networks:
      - msa-action-network
    depends_on:
      - msa-skywalking-oap

networks:
  msa-action-network:
    name: msa-action-network  # 不指定名称的话总是会将当前文件夹名作为网络名前缀
    driver: bridge
